import { Router } from 'express';
import { healthRouter } from './health.js';
import { authRouter } from '../domain/auth/auth.routes.js';
import { usersRouter } from '../domain/users/users.routes.js';
import { itemsRouter } from '../domain/items/items.routes.js';
import { inventoryRouter } from '../domain/inventory/inventory.routes.js';
import { customersRouter } from '../domain/customers/customers.routes.js';
import { salesRouter } from '../domain/sales/sales.routes.js';
import { financeRouter } from '../domain/finance/finance.routes.js';
import { notificationsRouter } from '../domain/notifications/notifications.routes.js';
import { reportsRouter } from '../domain/reports/reports.routes.js';
import { ownerRouter } from '../domain/owner/owner.routes.js';
import { settingsRouter } from '../domain/settings/settings.routes.js';
import { permissionsRouter } from '../domain/permissions/permissions.routes.js';
import { approvalsRouter } from '../domain/approvals/approvals.routes.js';
import { adminRouter } from '../domain/admin/admin.routes.js';
import { codesRouter } from '../domain/codes/codes.routes.js';

export const apiRouter = Router();
apiRouter.use('/health',       healthRouter);
apiRouter.use('/auth',         authRouter);
apiRouter.use('/users',        usersRouter);
apiRouter.use('/',             itemsRouter);
apiRouter.use('/',             inventoryRouter);
apiRouter.use('/',             customersRouter);
apiRouter.use('/',             salesRouter);
apiRouter.use('/',             financeRouter);
apiRouter.use('/notifications',notificationsRouter);
apiRouter.use('/reports',      reportsRouter);
apiRouter.use('/owner',        ownerRouter);
apiRouter.use('/settings',     settingsRouter);
apiRouter.use('/permissions',  permissionsRouter);
apiRouter.use('/approvals',    approvalsRouter);
apiRouter.use('/admin',        adminRouter);
apiRouter.use('/codes',        codesRouter);
